spring:
  application:
    name: BeerPong

  datasource:
    url: jdbc:mysql://${MYSQLHOST:localhost}:${MYSQLPORT:3307}/${MYSQLDATABASE:BeerPong}?createDatabaseIfNotExist=true
    username: ${MYSQLUSER:root}
    password: ${MYSQLPASSWORD:}
    driver-class-name: com.mysql.cj.jdbc.Driver
  
  jpa:
    database-platform: org.hibernate.dialect.MySQLDialect
    hibernate:
      ddl-auto: update
    show-sql: true

server:
  port: 8081
